<?php
/**
 * @file
 * A block containing a link to the parent of a well formed path
 */
 
 /**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function retreatrobot_help($path, $arg) {
  switch ($path) {
    case "admin/help#retreatrobot":
      return '<p>'.  t("A module aiding the maintenance of weekly CiviCRM events") .'</p>';
      break;
  }
}
 
 /**
 * Implements hook_block_info().
 */
function retreatrobot_block_info() {
  $blocks['retreatrobot'] = array(
    'info' => t('Retreat Robot'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

/**
 * Implements hook_menu().
 */
function retreatrobot_menu() {
  $items = array();  

  $items['admin/config/content/retreatrobot'] = array(
    'title' => 'Retreat Robot',
    'description' => 'Configuration for Retreat Robot',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('retreatrobot_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}  

function retreatrobot_form($form, &$form_state) {
  $form['retreatrobot_weeks'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of weeks'),
    '#default_value' => variable_get('retreatrobot_weeks', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t(' under development'),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}


?>